# Generated by Django 4.2.5 on 2023-09-20 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_lessonviewing_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lessonviewing",
            unique_together={("lesson", "user")},
        ),
    ]
