# Generated by Django 4.2.5 on 2023-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_lessonviewing_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="products",
            field=models.ManyToManyField(related_name="lessons", to="main.product"),
        ),
    ]
