# Generated by Django 4.2.5 on 2023-09-21 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_alter_lessonviewing_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productaccess",
            unique_together={("product", "user")},
        ),
    ]
